"""
This file is automatically generated by xDSL and not meant to be modified.

It was generated from /home/chendong/wangjie/work/projects/triton-xdsl-plugin/scripts/../dialects/TritonDialect.td.json
"""

# ruff: noqa: F403, F405

from xdsl.dialects.builtin import *
from xdsl.ir import *
from xdsl.irdl import *


@irdl_attr_definition
class TT_PtrType(ParametrizedAttribute, TypeAttribute):
    """Pointer type (`::mlir::triton::PointerType`) in Triton IR type system"""

    name = "tt.ptr"


@irdl_attr_definition
class TT_TensorDescType(ParametrizedAttribute, TypeAttribute):
    """Tensor descriptor type (`::mlir::triton::TensorDescType`) in Triton IR type system"""

    name = "tt.tensordesc"


Triton_Dialect = Dialect(
    "tt",
    [],
    [
        TT_PtrType,
        TT_TensorDescType,
    ],
)
