"""
This file is automatically generated by xDSL and not meant to be modified.

It was generated from /home/chendong/wangjie/work/projects/triton-xdsl-plugin/scripts/../dialects/TritonOps.td.json
"""

# ruff: noqa: F403, F405

from xdsl.dialects.builtin import *
from xdsl.ir import *
from xdsl.irdl import *


@irdl_attr_definition
class TT_PtrType(ParametrizedAttribute, TypeAttribute):
    """Pointer type (`::mlir::triton::PointerType`) in Triton IR type system"""

    name = "tt.ptr"


@irdl_attr_definition
class TT_TensorDescType(ParametrizedAttribute, TypeAttribute):
    """Tensor descriptor type (`::mlir::triton::TensorDescType`) in Triton IR type system"""

    name = "tt.tensordesc"


@irdl_op_definition
class CallOp(IRDLOperation):
    """call operation"""

    name = "tt.call"

    assembly_format = """
        $callee `(` $operands `)` attr-dict `:` functional-type($operands, results)
      """

    callee = prop_def(AnyAttr())

    operands = var_operand_def(AnyAttr())

    arg_attrs = opt_prop_def(AnyAttr())

    res_attrs = opt_prop_def(AnyAttr())

    v1 = var_result_def(AnyAttr())


@irdl_op_definition
class FuncOp(IRDLOperation):
    """An operation with a name containing a single `SSACFG` region"""

    name = "tt.func"

    sym_name = prop_def(SymbolNameConstraint())

    function_type = prop_def(AnyAttr())

    sym_visibility = opt_prop_def(BaseAttr(StringAttr))

    arg_attrs = opt_prop_def(AnyAttr())

    res_attrs = opt_prop_def(AnyAttr())

    body = region_def()


@irdl_op_definition
class ReturnOp(IRDLOperation):
    """Function return operation"""

    name = "tt.return"

    assembly_format = """attr-dict ($srcs^ `:` type($srcs))?"""

    srcs = var_operand_def(AnyAttr())


@irdl_op_definition
class TT_AddPtrOp(IRDLOperation):
    name = "tt.addptr"

    assembly_format = (
        """$ptr `,` $offset attr-dict `:` type($result) `,` type($offset)"""
    )

    ptr = operand_def(AnyOf((AnyAttr(), AnyAttr())))

    offset = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        EqAttrConstraint(IntegerType(1)),
                        EqAttrConstraint(IntegerType(4)),
                        EqAttrConstraint(IntegerType(8)),
                        EqAttrConstraint(IntegerType(16)),
                        EqAttrConstraint(IntegerType(32)),
                        EqAttrConstraint(IntegerType(64)),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    result = result_def(AnyOf((AnyAttr(), AnyAttr())))


@irdl_op_definition
class TT_AdvanceOp(IRDLOperation):
    """Advance a tensor pointer by offsets"""

    name = "tt.advance"

    assembly_format = """$ptr `,` `[` $offsets `]` attr-dict `:` type($result)"""

    ptr = operand_def(AnyAttr())

    offsets = var_operand_def(EqAttrConstraint(IntegerType(32)))

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_AssertOp(IRDLOperation):
    """Device-side assert, as in CUDA for correctness checking"""

    name = "tt.assert"

    assembly_format = """$condition `,` $message attr-dict `:` type($condition)"""

    condition = operand_def(AnyOf((EqAttrConstraint(IntegerType(1)), AnyAttr())))

    message = prop_def(BaseAttr(StringAttr))


@irdl_op_definition
class TT_AtomicCASOp(IRDLOperation):
    """atomic cas"""

    name = "tt.atomic_cas"

    assembly_format = """
          $sem `,` $scope `,` $ptr `,` $cmp `,` $val attr-dict `:`
          functional-type(operands, $result)
         """

    ptr = prop_def(AnyAttr())

    cmp = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    val = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    sem = prop_def(AnyAttr())

    scope = prop_def(AnyAttr())

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_AtomicRMWOp(IRDLOperation):
    """atomic rmw"""

    name = "tt.atomic_rmw"

    assembly_format = """
          $atomic_rmw_op `,` $sem `,` $scope `,` $ptr `,` $val (`,` $mask^)?  attr-dict `:`
          functional-type(operands, $result)
        """

    atomic_rmw_op = prop_def(AnyAttr())

    ptr = prop_def(AnyAttr())

    val = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    mask = opt_operand_def(AnyOf((EqAttrConstraint(IntegerType(1)), AnyAttr())))

    sem = prop_def(AnyAttr())

    scope = prop_def(AnyAttr())

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_BitcastOp(IRDLOperation):
    """Cast between types of the same bitwidth"""

    name = "tt.bitcast"

    assembly_format = """$src attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_BroadcastOp(IRDLOperation):
    """broadcast a tensor"""

    name = "tt.broadcast"

    assembly_format = """$src attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(AnyAttr())

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_CatOp(IRDLOperation):
    """concatenate 2 tensors"""

    name = "tt.cat"

    assembly_format = """$lhs `,` $rhs attr-dict `:` type($lhs) `->` type($result)"""

    lhs = operand_def(AnyAttr())

    rhs = operand_def(AnyAttr())

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_ClampFOp(IRDLOperation):
    """Clamp operation for floating point types"""

    name = "tt.clampf"

    assembly_format = """$x `,` $min `,` $max `,` `propagateNan` `=` $propagateNan attr-dict `:` type($result)"""

    x = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    min = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    max = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    propagateNan = prop_def(AnyAttr())

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_DescriptorGatherOp(IRDLOperation):
    """gather multiple rows from a descriptor into a single tensor"""

    name = "tt.descriptor_gather"

    assembly_format = """
        $desc `[` $x_offsets `,` $y_offset `]`
        attr-dict `:` functional-type(operands, results)
      """

    desc = prop_def(AnyAttr())

    x_offsets = operand_def(AnyAttr())

    y_offset = operand_def(EqAttrConstraint(IntegerType(32)))

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_DescriptorLoadOp(IRDLOperation):
    """Load from descriptor"""

    name = "tt.descriptor_load"

    assembly_format = """
        $desc `[` $indices `]`
        oilist(
          `cacheModifier` `=` $cache |
          `evictionPolicy` `=` $evict
        )
        attr-dict `:` qualified(type($desc)) `->` type($result)
      """

    desc = prop_def(AnyAttr())

    indices = var_operand_def(EqAttrConstraint(IntegerType(32)))

    cache = prop_def(AnyAttr())

    evict = prop_def(AnyAttr())

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_DescriptorReduceOp(IRDLOperation):
    """performs a reducing store operation based on a descriptor"""

    name = "tt.descriptor_reduce"

    assembly_format = """
        $kind `,` $desc `[` $indices `]` `,` $src
        attr-dict `:` qualified(type($desc)) `,` type($src)
      """

    kind = prop_def(AnyAttr())

    desc = prop_def(AnyAttr())

    src = operand_def(AnyAttr())

    indices = var_operand_def(EqAttrConstraint(IntegerType(32)))


@irdl_op_definition
class TT_DescriptorScatterOp(IRDLOperation):
    """scatter multiple rows to a descriptor from a single tensor"""

    name = "tt.descriptor_scatter"

    assembly_format = """
        $desc `[` $x_offsets `,` $y_offset `]` `,` $src
        attr-dict `:` type(operands)
      """

    desc = prop_def(AnyAttr())

    x_offsets = operand_def(AnyAttr())

    y_offset = operand_def(EqAttrConstraint(IntegerType(32)))

    src = operand_def(AnyAttr())


@irdl_op_definition
class TT_DescriptorStoreOp(IRDLOperation):
    """store value based on descriptor"""

    name = "tt.descriptor_store"

    assembly_format = """
        $desc `[` $indices `]` `,` $src
        attr-dict `:` qualified(type($desc)) `,` type($src)
      """

    desc = prop_def(AnyAttr())

    src = operand_def(AnyAttr())

    indices = var_operand_def(EqAttrConstraint(IntegerType(32)))


@irdl_op_definition
class TT_DotOp(IRDLOperation):
    """dot"""

    name = "tt.dot"

    assembly_format = """
          $a`,` $b`,` $c (`,` `inputPrecision` `=` $inputPrecision^)? attr-dict `:`
          type($a) `*` type($b) `->` type($d)
        """

    a = operand_def(AnyAttr())

    b = operand_def(AnyAttr())

    c = operand_def(AnyAttr())

    inputPrecision = prop_def(AnyAttr())

    maxNumImpreciseAcc = prop_def(AnyAttr())

    d = result_def(AnyAttr())


@irdl_op_definition
class TT_DotScaledOp(IRDLOperation):
    """dot_scaled"""

    name = "tt.dot_scaled"

    assembly_format = """
          $a (`scale` $a_scale^)? `,` $b (`scale` $b_scale^)? `,` $c
          `lhs` `=` $a_elem_type `rhs` `=` $b_elem_type attr-dict
          `:` type($a) (`,` type($a_scale)^)? `*` type($b) (`,` type($b_scale)^)? `->` type($d)
        """

    a = operand_def(AnyAttr())

    b = operand_def(AnyAttr())

    c = operand_def(AnyAttr())

    a_scale = opt_operand_def(AnyAttr())

    b_scale = opt_operand_def(AnyAttr())

    a_elem_type = prop_def(AnyAttr())

    b_elem_type = prop_def(AnyAttr())

    fastMath = prop_def(BaseAttr(BoolAttr))

    lhs_k_pack = prop_def(AnyAttr())

    rhs_k_pack = prop_def(AnyAttr())

    d = result_def(AnyAttr())


@irdl_op_definition
class TT_ElementwiseInlineAsmOp(IRDLOperation):
    """inline assembly applying an elementwise operation to a group of packed elements."""

    name = "tt.elementwise_inline_asm"

    assembly_format = """
        $asm_string attr-dict ($args^ `:` type($args))? `->` type($result)
      """

    asm_string = prop_def(BaseAttr(StringAttr))

    constraints = prop_def(BaseAttr(StringAttr))

    pure = prop_def(BaseAttr(BoolAttr))

    packed_element = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    args = var_operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyOf(
                                    (
                                        AnyAttr(),
                                        AnyAttr(),
                                        AnyAttr(),
                                        AnyAttr(),
                                        EqAttrConstraint(Float16Type()),
                                        EqAttrConstraint(BFloat16Type()),
                                        EqAttrConstraint(Float32Type()),
                                        EqAttrConstraint(Float64Type()),
                                    )
                                ),
                                AnyAttr(),
                            )
                        ),
                        AnyOf(
                            (
                                AnyOf(
                                    (
                                        EqAttrConstraint(IntegerType(1)),
                                        EqAttrConstraint(IntegerType(4)),
                                        EqAttrConstraint(IntegerType(8)),
                                        EqAttrConstraint(IntegerType(16)),
                                        EqAttrConstraint(IntegerType(32)),
                                        EqAttrConstraint(IntegerType(64)),
                                    )
                                ),
                                AnyAttr(),
                            )
                        ),
                        AnyOf((AnyAttr(), AnyAttr())),
                        AnyAttr(),
                    )
                )
            )
        )
    )

    result = var_result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_ExpandDimsOp(IRDLOperation):
    """expand_dims"""

    name = "tt.expand_dims"

    assembly_format = """$src attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(AnyAttr())

    axis = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_ExternElementwiseOp(IRDLOperation):
    name = "tt.extern_elementwise"

    assembly_format = """operands attr-dict `:` functional-type(operands, $result)"""

    srcs = var_operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    libname = prop_def(BaseAttr(StringAttr))

    libpath = prop_def(BaseAttr(StringAttr))

    symbol = prop_def(BaseAttr(StringAttr))

    pure = prop_def(BaseAttr(BoolAttr))

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_FpToFpOp(IRDLOperation):
    """Floating point casting for custom types"""

    name = "tt.fp_to_fp"

    assembly_format = """$src attr-dict  (`,` `rounding` `=` $rounding^)? `:` type($src) `->` type($result)"""

    src = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    rounding = opt_prop_def(AnyAttr())

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_GatherOp(IRDLOperation):
    """local gather operation"""

    name = "tt.gather"

    assembly_format = """
        $src `[` $indices `]` attr-dict `:`
        functional-type(operands, results)
      """

    src = operand_def(AnyAttr())

    indices = operand_def(AnyAttr())

    axis = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    efficient_layout = prop_def(EqAttrConstraint(UnitAttr()))

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_GetNumProgramsOp(IRDLOperation):
    name = "tt.get_num_programs"

    assembly_format = """$axis attr-dict `:` type($result)"""

    axis = prop_def(AnyAttr())

    result = result_def(EqAttrConstraint(IntegerType(32)))


@irdl_op_definition
class TT_GetProgramIdOp(IRDLOperation):
    name = "tt.get_program_id"

    assembly_format = """$axis attr-dict `:` type($result)"""

    axis = prop_def(AnyAttr())

    result = result_def(EqAttrConstraint(IntegerType(32)))


@irdl_op_definition
class TT_HistogramOp(IRDLOperation):
    """return a histogram of the inputs."""

    name = "tt.histogram"

    assembly_format = """
        $src (`,` $mask^)? attr-dict `:` type($src) `->` type($result)
      """

    src = operand_def(AnyAttr())

    mask = opt_operand_def(AnyOf((EqAttrConstraint(IntegerType(1)), AnyAttr())))

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_IntToPtrOp(IRDLOperation):
    """Cast int64 to pointer"""

    name = "tt.int_to_ptr"

    assembly_format = """$src attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(AnyOf((EqAttrConstraint(IntegerType(64)), AnyAttr())))

    result = result_def(AnyOf((AnyAttr(), AnyAttr())))


@irdl_op_definition
class TT_JoinOp(IRDLOperation):
    """join two tensors along a new, minor dimension"""

    name = "tt.join"

    assembly_format = """$lhs `,` $rhs attr-dict `:` type($lhs) `->` type($result)"""

    lhs = operand_def(AnyAttr())

    rhs = operand_def(AnyAttr())

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_LoadOp(IRDLOperation):
    """Load from a tensor of pointers or from a tensor pointer"""

    name = "tt.load"

    assembly_format = """
          $ptr (`,` $mask^)? (`,` $other^)?
          oilist(
            `cacheModifier` `=` $cache |
            `evictionPolicy` `=` $evict
          )
          attr-dict `:` type($ptr)
        """

    ptr = operand_def(AnyOf((AnyOf((AnyAttr(), AnyAttr())), AnyAttr())))

    mask = opt_operand_def(AnyOf((EqAttrConstraint(IntegerType(1)), AnyAttr())))

    other = opt_operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    boundaryCheck = prop_def(AnyAttr())

    padding = opt_prop_def(AnyAttr())

    cache = prop_def(AnyAttr())

    evict = prop_def(AnyAttr())

    isVolatile = prop_def(AnyAttr())

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_MakeRangeOp(IRDLOperation):
    """make range"""

    name = "tt.make_range"

    assembly_format = """attr-dict `:` type($result)"""

    start = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    end = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_MakeTensorDescOp(IRDLOperation):
    """Make a tensor descriptor type with meta information of the parent tensor and block size"""

    name = "tt.make_tensor_descriptor"

    assembly_format = """$base `,` `[` $shape `]` `,` `[` $strides `]` attr-dict `:` type($base) `,` type($result)"""

    base = operand_def(AnyAttr())

    shape = var_operand_def(EqAttrConstraint(IntegerType(32)))

    strides = var_operand_def(EqAttrConstraint(IntegerType(64)))

    padding = prop_def(AnyAttr())

    result = result_def(BaseAttr(TT_TensorDescType))


@irdl_op_definition
class TT_MakeTensorPtrOp(IRDLOperation):
    """Make a tensor pointer type with meta information of the parent tensor and the block specified"""

    name = "tt.make_tensor_ptr"

    assembly_format = """$base `,` `[` $shape `]` `,` `[` $strides `]` `,` `[` $offsets `]` attr-dict `:` type($result)"""

    base = operand_def(AnyAttr())

    shape = var_operand_def(EqAttrConstraint(IntegerType(64)))

    strides = var_operand_def(EqAttrConstraint(IntegerType(64)))

    offsets = var_operand_def(EqAttrConstraint(IntegerType(32)))

    order = prop_def(AnyAttr())

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_MapElementwiseOp(IRDLOperation):
    """Map a scalar subregion over a tensor"""

    name = "tt.map_elementwise"

    srcs = var_operand_def(AnyAttr())

    pack = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    result = var_result_def(AnyAttr())

    scalarOp = region_def()


@irdl_op_definition
class TT_MapElementwiseReturnOp(IRDLOperation):
    """terminator for map elementwise operator"""

    name = "tt.map_elementwise.return"

    assembly_format = """attr-dict ($result^ `:` type($result))?"""

    result = var_operand_def(AnyAttr())


@irdl_op_definition
class TT_MulhiUIOp(IRDLOperation):
    """Most significant N bits of the 2N-bit product of two integers"""

    name = "tt.mulhiui"

    assembly_format = """$x `,` $y attr-dict `:` type($x)"""

    x = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        EqAttrConstraint(IntegerType(1)),
                        EqAttrConstraint(IntegerType(4)),
                        EqAttrConstraint(IntegerType(8)),
                        EqAttrConstraint(IntegerType(16)),
                        EqAttrConstraint(IntegerType(32)),
                        EqAttrConstraint(IntegerType(64)),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    y = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        EqAttrConstraint(IntegerType(1)),
                        EqAttrConstraint(IntegerType(4)),
                        EqAttrConstraint(IntegerType(8)),
                        EqAttrConstraint(IntegerType(16)),
                        EqAttrConstraint(IntegerType(32)),
                        EqAttrConstraint(IntegerType(64)),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        EqAttrConstraint(IntegerType(1)),
                        EqAttrConstraint(IntegerType(4)),
                        EqAttrConstraint(IntegerType(8)),
                        EqAttrConstraint(IntegerType(16)),
                        EqAttrConstraint(IntegerType(32)),
                        EqAttrConstraint(IntegerType(64)),
                    )
                ),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_PreciseDivFOp(IRDLOperation):
    """Precise div for floating point types"""

    name = "tt.precise_divf"

    assembly_format = """$x `,` $y attr-dict `:` type($x)"""

    x = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    y = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_PreciseSqrtOp(IRDLOperation):
    """Precise sqrt for floating point types"""

    name = "tt.precise_sqrt"

    assembly_format = """$x attr-dict `:` type($x)"""

    x = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        AnyAttr(),
                        EqAttrConstraint(Float16Type()),
                        EqAttrConstraint(BFloat16Type()),
                        EqAttrConstraint(Float32Type()),
                        EqAttrConstraint(Float64Type()),
                    )
                ),
                AnyAttr(),
            )
        )
    )


@irdl_op_definition
class TT_PrintOp(IRDLOperation):
    """Device-side print, as in CUDA for debugging"""

    name = "tt.print"

    assembly_format = """
        $prefix attr-dict (`:` $args^ `:` type($args))?
      """

    prefix = prop_def(BaseAttr(StringAttr))

    hex = prop_def(BaseAttr(BoolAttr))

    args = var_operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyOf(
                                    (
                                        AnyAttr(),
                                        AnyAttr(),
                                        AnyAttr(),
                                        AnyAttr(),
                                        EqAttrConstraint(Float16Type()),
                                        EqAttrConstraint(BFloat16Type()),
                                        EqAttrConstraint(Float32Type()),
                                        EqAttrConstraint(Float64Type()),
                                    )
                                ),
                                AnyAttr(),
                            )
                        ),
                        AnyOf(
                            (
                                AnyOf(
                                    (
                                        EqAttrConstraint(IntegerType(1)),
                                        EqAttrConstraint(IntegerType(4)),
                                        EqAttrConstraint(IntegerType(8)),
                                        EqAttrConstraint(IntegerType(16)),
                                        EqAttrConstraint(IntegerType(32)),
                                        EqAttrConstraint(IntegerType(64)),
                                    )
                                ),
                                AnyAttr(),
                            )
                        ),
                        AnyOf((AnyAttr(), AnyAttr())),
                        AnyAttr(),
                    )
                )
            )
        )
    )

    isSigned = prop_def(AnyAttr())


@irdl_op_definition
class TT_PtrToIntOp(IRDLOperation):
    """Cast pointer to int64"""

    name = "tt.ptr_to_int"

    assembly_format = """$src attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(AnyOf((AnyAttr(), AnyAttr())))

    result = result_def(AnyOf((EqAttrConstraint(IntegerType(64)), AnyAttr())))


@irdl_op_definition
class TT_ReduceOp(IRDLOperation):
    """Reduction using generic combination algorithm"""

    name = "tt.reduce"

    srcs = var_operand_def(AnyAttr())

    axis = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    result = var_result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    combineOp = region_def("single_block")


@irdl_op_definition
class TT_ReduceReturnOp(IRDLOperation):
    """terminator for reduce operator"""

    name = "tt.reduce.return"

    assembly_format = """$result attr-dict `:` type($result)"""

    result = var_operand_def(AnyAttr())


@irdl_op_definition
class TT_ReshapeOp(IRDLOperation):
    """reinterpret a tensor to a different shape. It may change elements order if the attribute is set."""

    name = "tt.reshape"

    assembly_format = """$src (`allow_reorder` $allow_reorder^)? (`efficient_layout` $efficient_layout^)? attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(AnyAttr())

    allow_reorder = prop_def(EqAttrConstraint(UnitAttr()))

    efficient_layout = prop_def(EqAttrConstraint(UnitAttr()))

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_ScanOp(IRDLOperation):
    """Associative scan using generic combination algorithm"""

    name = "tt.scan"

    srcs = var_operand_def(AnyAttr())

    axis = prop_def(IntegerAttr.constr(EqAttrConstraint(IntegerType(32))))

    reverse = prop_def(BaseAttr(BoolAttr))

    result = var_result_def(AnyAttr())

    combineOp = region_def("single_block")


@irdl_op_definition
class TT_ScanReturnOp(IRDLOperation):
    """terminator for scan operator"""

    name = "tt.scan.return"

    assembly_format = """$result attr-dict `:` type($result)"""

    result = var_operand_def(AnyAttr())


@irdl_op_definition
class TT_SplatOp(IRDLOperation):
    """splat"""

    name = "tt.splat"

    assembly_format = """$src attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_SplitOp(IRDLOperation):
    """splits a tensor into two, along its last dimension"""

    name = "tt.split"

    assembly_format = """$src attr-dict `:` type($src) `->` type($outLHS)"""

    src = operand_def(AnyAttr())

    outLHS = result_def(AnyAttr())

    outRHS = result_def(AnyAttr())


@irdl_op_definition
class TT_StoreOp(IRDLOperation):
    """Store by a tensor of pointers or by a tensor pointer"""

    name = "tt.store"

    assembly_format = """
          $ptr `,` $value (`,` $mask^)?
          oilist(`cacheModifier` `=` $cache | `evictionPolicy` `=` $evict)
          attr-dict `:` type($ptr)
        """

    ptr = prop_def(AnyAttr())

    value = operand_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )

    mask = opt_operand_def(AnyOf((EqAttrConstraint(IntegerType(1)), AnyAttr())))

    boundaryCheck = prop_def(AnyAttr())

    cache = prop_def(AnyAttr())

    evict = prop_def(AnyAttr())


@irdl_op_definition
class TT_TransOp(IRDLOperation):
    """rearrange the dimensions of a tensor"""

    name = "tt.trans"

    assembly_format = """$src attr-dict `:` type($src) `->` type($result)"""

    src = operand_def(AnyAttr())

    order = prop_def(AnyAttr())

    result = result_def(AnyAttr())


@irdl_op_definition
class TT_UnsplatOp(IRDLOperation):
    """convert a tensor with a single element to a scalar"""

    name = "tt.unsplat"

    assembly_format = """$src attr-dict `:` type($src)"""

    src = operand_def(AnyAttr())

    result = result_def(
        AnyOf(
            (
                AnyOf(
                    (
                        AnyOf(
                            (
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                AnyAttr(),
                                EqAttrConstraint(Float16Type()),
                                EqAttrConstraint(BFloat16Type()),
                                EqAttrConstraint(Float32Type()),
                                EqAttrConstraint(Float64Type()),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf(
                    (
                        AnyOf(
                            (
                                EqAttrConstraint(IntegerType(1)),
                                EqAttrConstraint(IntegerType(4)),
                                EqAttrConstraint(IntegerType(8)),
                                EqAttrConstraint(IntegerType(16)),
                                EqAttrConstraint(IntegerType(32)),
                                EqAttrConstraint(IntegerType(64)),
                            )
                        ),
                        AnyAttr(),
                    )
                ),
                AnyOf((AnyAttr(), AnyAttr())),
                AnyAttr(),
            )
        )
    )


Triton_Dialect = Dialect(
    "tt",
    [
        CallOp,
        FuncOp,
        ReturnOp,
        TT_AddPtrOp,
        TT_AdvanceOp,
        TT_AssertOp,
        TT_AtomicCASOp,
        TT_AtomicRMWOp,
        TT_BitcastOp,
        TT_BroadcastOp,
        TT_CatOp,
        TT_ClampFOp,
        TT_DescriptorGatherOp,
        TT_DescriptorLoadOp,
        TT_DescriptorReduceOp,
        TT_DescriptorScatterOp,
        TT_DescriptorStoreOp,
        TT_DotOp,
        TT_DotScaledOp,
        TT_ElementwiseInlineAsmOp,
        TT_ExpandDimsOp,
        TT_ExternElementwiseOp,
        TT_FpToFpOp,
        TT_GatherOp,
        TT_GetNumProgramsOp,
        TT_GetProgramIdOp,
        TT_HistogramOp,
        TT_IntToPtrOp,
        TT_JoinOp,
        TT_LoadOp,
        TT_MakeRangeOp,
        TT_MakeTensorDescOp,
        TT_MakeTensorPtrOp,
        TT_MapElementwiseOp,
        TT_MapElementwiseReturnOp,
        TT_MulhiUIOp,
        TT_PreciseDivFOp,
        TT_PreciseSqrtOp,
        TT_PrintOp,
        TT_PtrToIntOp,
        TT_ReduceOp,
        TT_ReduceReturnOp,
        TT_ReshapeOp,
        TT_ScanOp,
        TT_ScanReturnOp,
        TT_SplatOp,
        TT_SplitOp,
        TT_StoreOp,
        TT_TransOp,
        TT_UnsplatOp,
    ],
    [
        TT_PtrType,
        TT_TensorDescType,
    ],
)
